// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: src/grpc/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LamportMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportTimestamp int64                  `protobuf:"varint,1,opt,name=Lamport_timestamp,json=LamportTimestamp,proto3" json:"Lamport_timestamp,omitempty"`
	ProcessId        int64                  `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LamportMessage) Reset() {
	*x = LamportMessage{}
	mi := &file_src_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamportMessage) ProtoMessage() {}

func (x *LamportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamportMessage.ProtoReflect.Descriptor instead.
func (*LamportMessage) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *LamportMessage) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *LamportMessage) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_proto_rawDescGZIP(), []int{1}
}

var File_src_grpc_proto_proto protoreflect.FileDescriptor

const file_src_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x14src/grpc/proto.proto\"\\\n" +
	"\x0eLamportMessage\x12+\n" +
	"\x11Lamport_timestamp\x18\x01 \x01(\x03R\x10LamportTimestamp\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\x03R\tprocessId\"\a\n" +
	"\x05Empty2d\n" +
	"\x04Node\x12\"\n" +
	"\aRequest\x12\x0f.LamportMessage\x1a\x06.Empty\x12 \n" +
	"\x05Reply\x12\x0f.LamportMessage\x1a\x06.Empty\x12\x16\n" +
	"\x04Ping\x12\x06.Empty\x1a\x06.EmptyB\x1aZ\x18Assignment-03/grpc/protob\x06proto3"

var (
	file_src_grpc_proto_proto_rawDescOnce sync.Once
	file_src_grpc_proto_proto_rawDescData []byte
)

func file_src_grpc_proto_proto_rawDescGZIP() []byte {
	file_src_grpc_proto_proto_rawDescOnce.Do(func() {
		file_src_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_grpc_proto_proto_rawDesc), len(file_src_grpc_proto_proto_rawDesc)))
	})
	return file_src_grpc_proto_proto_rawDescData
}

var file_src_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_grpc_proto_proto_goTypes = []any{
	(*LamportMessage)(nil), // 0: LamportMessage
	(*Empty)(nil),          // 1: Empty
}
var file_src_grpc_proto_proto_depIdxs = []int32{
	0, // 0: Node.Request:input_type -> LamportMessage
	0, // 1: Node.Reply:input_type -> LamportMessage
	1, // 2: Node.Ping:input_type -> Empty
	1, // 3: Node.Request:output_type -> Empty
	1, // 4: Node.Reply:output_type -> Empty
	1, // 5: Node.Ping:output_type -> Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_grpc_proto_proto_init() }
func file_src_grpc_proto_proto_init() {
	if File_src_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_grpc_proto_proto_rawDesc), len(file_src_grpc_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_proto_proto_goTypes,
		DependencyIndexes: file_src_grpc_proto_proto_depIdxs,
		MessageInfos:      file_src_grpc_proto_proto_msgTypes,
	}.Build()
	File_src_grpc_proto_proto = out.File
	file_src_grpc_proto_proto_goTypes = nil
	file_src_grpc_proto_proto_depIdxs = nil
}
